version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      - run: 
          name: "Setup custom environment variables"
          command: sudo chmod +x ./qualiti-script.sh && sudo ./qualiti-script.sh
